// Generated by Wrangler on Wed Aug 07 2024 13:24:25 GMT-0700 (Pacific Daylight Time)
// by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	sse_weather_app_test: KVNamespace;
	WEBFLOW_DOMAIN: "https://thind-styleguide-v2-766e0fe6400f2a5409b.webflow.io/";
	GOOGLE_PLACES_API_KEY: string;
}
